### ISSUE TITLE
Sorry, i am new to pynq board. 

### ISSUE THREAD

**Issue by tim7107** [twaclaw/matmult#2]

**Comment by tim7107** [comment]
Hi,i am new to pynq board.
I want to write matrix multiplication custom pynq overlay for ultra96 v2 board.
But i do not know if there is any code tutorial for vivado HLS cpp version. 
I am not familiar to hardware field!
Hope someone can give me some advice!
Thanks a lot!
Tim

**Comment by twaclaw** [comment]
Hi Tim, 

Sorry for the belated reply. 
I am not really an expert on the topic, I created this example to familiarize myself with HLS. 

I think you only need to modify/recreate the  [boards/Pynq-Z1/matmult/](https://github.com/twaclaw/matmult/tree/master/boards/Pynq-Z1/matmult) wrapper for your particular board, and use the same kernel in [hls](https://github.com/twaclaw/matmult/tree/master/hls), which implements the matrix multiplication.  

Open the project with Vivado and modify it, or create a new one and try to define similar connections. You don't need to wire all the connections manually, most of the wiring is done automatically in Vivado.

Hope that helps,

Best,
Medrano.

**Comment by tim7107** [comment]
Hi twaclaw, thanks for your helping!
I am now trying to applied your matmul.cpp  to see whether it works on my ultra96 v2 board.
Beacuse i do not know how to add the head file to the project.
Hence, I have combined the head file code into matmul.cpp  just like below. 
![image](https://user-images.githubusercontent.com/61227032/89902787-75fc8d00-dc19-11ea-842f-7b5358a57240.png)
Can you give some advice that why the ap_int can not be resolved?
Thanks a lot!!!!
I have no idea about hardware, but i will try my best to understand it.
Tim

**Comment by tim7107** [comment]
The mistake disappear after i just run C synthesis. Is that OK? XD

**Comment by tim7107** [comment]
![image](https://user-images.githubusercontent.com/61227032/89920283-ccc09180-dc2e-11ea-9df9-48bf31b351fb.png)
I just create the design using Vivado to connect the matmul overlay with the hardware design!
Do you know what happened here? Will it affect the usage of dma?
Thanks for your helping!!

**Comment by twaclaw** [comment]
Hi @tim7107,
I think it would be better to ask those questions in the PYNQ or in a vivado forum.
Sorry I cannot help you any further.  My suggestion is to try to compile the code as it is, for the PYNQ-Z1 board, and only then, when you verify that the original version is working you start doing modifications. 

Best,
