### ISSUE TITLE
Overlay files work one their own but newly generated ones don't!

### ISSUE THREAD

**Issue by sarashs** [twaclaw/matmult#3]
Hi,

When I use your overlay files (tcl hwh bit) everything is good but when I recompile your hls code and generate the IP and then build it in Vivado myself the IP behaves in a weird way. Every other column in the output matrix is zero! This happens with all of the three versions of the project that you have as well as with the original floating multiplication tutorial that you use as a reference. I am wondering if you too had this or similar issues and if you have a solution about them. I don't know what I am missing. I also checked my block design against the PDF you have an it perfectly matches. I am guessing maybe the issue is with the DMA or Interconnect settings but I don't know. Any suggestions?

**Comment by sarashs** [comment]
Figured it out! I was using 32 bit HP0 AXI instead of 64 bit.

**Comment by twaclaw** [comment]
Great, glad it is working now.
